// lib/useExport.js
import { useCallback } from 'react';

export function useExport() {

  const exportPNG = useCallback(async (elementRef, filename = 'chart') => {
    try {
      const html2canvas = (await import('html2canvas')).default;
      const canvas = await html2canvas(elementRef, {
        backgroundColor: null,
        scale: 2,
        useCORS: true,
        allowTaint: true,
        logging: false,
      });
      const link = document.createElement('a');
      link.download = `${filename}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    } catch (err) {
      console.error('PNG export failed:', err);
    }
  }, []);

  const exportPDF = useCallback(async (elementRef, filename = 'chart', title = '') => {
    try {
      const html2canvas = (await import('html2canvas')).default;
      const { jsPDF }   = await import('jspdf');

      const canvas  = await html2canvas(elementRef, {
        backgroundColor: '#0D1225',
        scale: 2,
        useCORS: true,
        allowTaint: true,
        logging: false,
      });

      const imgData = canvas.toDataURL('image/png');
      const pdf     = new jsPDF({ orientation: 'landscape', unit: 'px', format: 'a4' });

      const pdfW  = pdf.internal.pageSize.getWidth();
      const pdfH  = pdf.internal.pageSize.getHeight();
      const ratio = Math.min(pdfW / canvas.width, pdfH / canvas.height) * 0.9;
      const imgW  = canvas.width  * ratio;
      const imgH  = canvas.height * ratio;
      const x     = (pdfW - imgW) / 2;
      const y     = title ? 40 : (pdfH - imgH) / 2;

      // Header
      pdf.setFillColor(13, 18, 37);
      pdf.rect(0, 0, pdfW, pdfH, 'F');

      if (title) {
        pdf.setFont('helvetica', 'bold');
        pdf.setFontSize(14);
        pdf.setTextColor(240, 240, 255);
        pdf.text(title, pdfW / 2, 24, { align: 'center' });

        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(9);
        pdf.setTextColor(120, 120, 160);
        pdf.text(`Generated by DataMind · ${new Date().toLocaleDateString()}`, pdfW / 2, 34, { align: 'center' });
      }

      pdf.addImage(imgData, 'PNG', x, y, imgW, imgH);
      pdf.save(`${filename}.pdf`);
    } catch (err) {
      console.error('PDF export failed:', err);
    }
  }, []);

  return { exportPNG, exportPDF };
}